// Generated by scripts/gen-asset-manifest.mjs — do not edit by hand.
// Rewritten automatically when the dev server starts, when art is added or
// removed while it is running, and at the start of every build.

export const assetManifest = {
  spells: ['default', 'arcane', 'earth', 'fire', 'water', 'wind'],
  totems: ['Dolbae', 'Magic_Parasite_Zoah', 'parasite_hunter_Yaharl', 'SilverFinal'],
  ui: ['title'],
} as const

/**
 * The filename behind each key, keyed "category/key". Art may be any
 * supported format and any capitalisation, so the name is recorded rather
 * than reconstructed from the key.
 */
export const assetFiles: Readonly<Record<string, string>> = {
  "spells/default": "default.webp",
  "spells/arcane": "arcane.webp",
  "spells/earth": "earth.webp",
  "spells/fire": "fire.webp",
  "spells/water": "water.webp",
  "spells/wind": "wind.webp",
  "totems/Dolbae": "Dolbae.webp",
  "totems/Magic_Parasite_Zoah": "Magic_Parasite_Zoah.webp",
  "totems/parasite_hunter_Yaharl": "parasite_hunter_Yaharl.webp",
  "totems/SilverFinal": "SilverFinal.webp",
  "ui/title": "title.webp"
}
