// Generated by scripts/gen-audio-manifest.mjs — do not edit by hand.
// Rewritten when the dev server starts, when audio is added or removed while
// it runs, and at the start of every build.

/** Cue names that have a file behind them, by folder. */
export const audioManifest = {
  music: ["battle","boss","dungeon","menu","rest","results"],
  ambient: ["drip","night","wind"],
  sfx: ["battleStart","bossDoor","cancel","chestOpen","confirm","correct","damage","defeat","diceRoll","discovery","enemyAppear","enemyAttack","itemUse","levelUp","move","npcTalk","playerAttack","reward","shrine","trapTrigger","victory","wrong"],
} as const

/**
 * Music a world ships for itself, by world id. A slot listed here overrides
 * the global track of the same name for runs in that world.
 */
export const worldMusic: Readonly<Record<string, readonly string[]>> = {}

/**
 * The file behind each cue, keyed by its path from public/. Cue names are
 * fixed; the file may be any format the browser decodes and any
 * capitalisation, so the name is recorded rather than reconstructed.
 */
export const audioFiles: Readonly<Record<string, string>> = {
  "audio/music/battle": "battle.wav",
  "audio/music/boss": "boss.wav",
  "audio/music/dungeon": "dungeon.wav",
  "audio/music/menu": "menu.wav",
  "audio/music/rest": "rest.wav",
  "audio/music/results": "results.wav",
  "audio/ambient/drip": "drip.wav",
  "audio/ambient/night": "night.wav",
  "audio/ambient/wind": "wind.wav",
  "audio/sfx/battleStart": "battleStart.wav",
  "audio/sfx/bossDoor": "bossDoor.wav",
  "audio/sfx/cancel": "cancel.wav",
  "audio/sfx/chestOpen": "chestOpen.wav",
  "audio/sfx/confirm": "confirm.wav",
  "audio/sfx/correct": "correct.wav",
  "audio/sfx/damage": "damage.wav",
  "audio/sfx/defeat": "defeat.wav",
  "audio/sfx/diceRoll": "diceRoll.wav",
  "audio/sfx/discovery": "discovery.wav",
  "audio/sfx/enemyAppear": "enemyAppear.wav",
  "audio/sfx/enemyAttack": "enemyAttack.wav",
  "audio/sfx/itemUse": "itemUse.wav",
  "audio/sfx/levelUp": "levelUp.wav",
  "audio/sfx/move": "move.wav",
  "audio/sfx/npcTalk": "npcTalk.wav",
  "audio/sfx/playerAttack": "playerAttack.wav",
  "audio/sfx/reward": "reward.wav",
  "audio/sfx/shrine": "shrine.wav",
  "audio/sfx/trapTrigger": "trapTrigger.wav",
  "audio/sfx/victory": "victory.wav",
  "audio/sfx/wrong": "wrong.wav"
}
