// Generated by scripts/gen-world-manifest.mjs — do not edit by hand.
// Rewritten when the dev server starts, when art under public/worlds is
// added or removed while it runs, and at the start of every build.

export interface WorldPack {
  id: string
  name: string
  description: string
  /** False when a required slot is missing; such a world is never offered. */
  complete: boolean
  /** Exactly what is missing, for the report shown to whoever is building it. */
  missing: readonly string[]
  locations: readonly string[]
  optionalLocations: readonly string[]
  events: readonly string[]
  npcs: readonly string[]
  enemies: readonly string[]
  bosses: readonly string[]
  /**
   * The file extension behind each slot, keyed "folder/slot". Worlds shipped
   * here are WebP; one dropped in as PNG and not yet optimized is PNG, and
   * both play the same.
   */
  ext: Readonly<Record<string, string>>
}

export const requiredLocations = ["entrance","corridor1","corridor2","keyRoom","restRoom","pathwayFork","shrineRoom","treasureRoom","trapRoom","bossRoom"] as const
export const requiredEvents = ["bossDoor","roadSign","key","trap1","trap2","treasureLocked","treasureOpened","treasureMimic","rest","shrineDoor"] as const
export const minNpcs = 3
export const minEnemies = 4

export const worldPacks: readonly WorldPack[] = [
  {
    id: "dragon-king",
    name: "용왕의 던전",
    description: "물에 잠긴 회랑과 금빛 보고. 깊은 곳에서 무언가가 기다립니다.",
    complete: true,
    missing: [],
    locations: ["battle","battle2","bossRoom","corridor1","corridor2","entrance","keyRoom","pathwayFork","restRoom","shrineRoom","trapRoom","treasureRoom"],
    optionalLocations: ["battle","battle2"],
    events: ["bossDoor","key","rest","roadSign","shrineDoor","trap1","trap2","treasureLocked","treasureMimic","treasureOpened"],
    npcs: ["hunter","merchant","pilgrim","scholar","wanderer"],
    enemies: ["goblin","slime","warden","wraith"],
    bosses: ["guardian"],
    ext: {"locations/battle":"webp","locations/battle2":"webp","locations/bossRoom":"webp","locations/corridor1":"webp","locations/corridor2":"webp","locations/entrance":"webp","locations/keyRoom":"webp","locations/pathwayFork":"webp","locations/restRoom":"webp","locations/shrineRoom":"webp","locations/trapRoom":"webp","locations/treasureRoom":"webp","events/bossDoor":"webp","events/key":"webp","events/rest":"webp","events/roadSign":"webp","events/shrineDoor":"webp","events/trap1":"webp","events/trap2":"webp","events/treasureLocked":"webp","events/treasureMimic":"webp","events/treasureOpened":"webp","npcs/hunter":"png","npcs/merchant":"png","npcs/pilgrim":"webp","npcs/scholar":"webp","npcs/wanderer":"webp","enemies/goblin":"webp","enemies/slime":"webp","enemies/warden":"webp","enemies/wraith":"webp","bosses/guardian":"webp"},
  },
  {
    id: "starter",
    name: "첫 번째 길",
    description: "조용한 연습용 던전. 아직 그려지지 않은 세계입니다.",
    complete: true,
    missing: [],
    locations: ["bossRoom","corridor1","corridor2","entrance","keyRoom","pathwayFork","restRoom","shrineRoom","trapRoom","treasureRoom"],
    optionalLocations: [],
    events: ["bossDoor","key","rest","roadSign","shrineDoor","trap1","trap2","treasureLocked","treasureMimic","treasureOpened"],
    npcs: ["merchant","scholar","wanderer"],
    enemies: ["brute","crawler","prowler","shade"],
    bosses: ["guardian"],
    ext: {"locations/bossRoom":"webp","locations/corridor1":"webp","locations/corridor2":"webp","locations/entrance":"webp","locations/keyRoom":"webp","locations/pathwayFork":"webp","locations/restRoom":"webp","locations/shrineRoom":"webp","locations/trapRoom":"webp","locations/treasureRoom":"webp","events/bossDoor":"webp","events/key":"webp","events/rest":"webp","events/roadSign":"webp","events/shrineDoor":"webp","events/trap1":"webp","events/trap2":"webp","events/treasureLocked":"webp","events/treasureMimic":"webp","events/treasureOpened":"webp","npcs/merchant":"png","npcs/scholar":"png","npcs/wanderer":"webp","enemies/brute":"webp","enemies/crawler":"webp","enemies/prowler":"webp","enemies/shade":"webp","bosses/guardian":"webp"},
  },
]
